# Alcritty colors
# Cutesome Colorscheme


[colors.primary]
background = "#ffffff"
foreground = "#121212"

[colors.cursor]
  text =  "CellForeground" 
  cursor = "#616161"

[colors.bright]
  black =   "#121212"
  red =     "#ff5252"
  green =   "#00c853"
  yellow =  "#f0ca3c"
  blue =    "#448aff"
  magenta = "#7c4dff"
  cyan =    "#18ffff"
  white =   "#bdbdbd"

[colors.normal]
  black =   "#121212"
  red =     "#ff5252"
  green =   "#00c853"
  yellow =  "#f0ca3c"
  blue =    "#448aff"
  magenta = "#7c4dff"
  cyan =    "#18ffff"
  white =   "#000000"
